### PR TITLE
Create github.io documentation page

### PR DESCRIPTION
**Pull request by kadinzhang**
Description
-----------
Created docs/ folder for github pages to read the README (index.md) and turn it into html.

For deployment:
> Visit your repository’s settings tab and select master branch /docs folder as the GitHub Pages source. Click save, and you’re done.

### CODE REVIEW

**Comment by jkeat** [comment]
@kadinzhang to clarify, is the idea here to move our current README content to github pages and replace the README with a link to this new page?

**Comment by kadinzhang** [comment]
Yep - I was thinking of something like [this](https://github.com/tensorflow/magenta-js): a quick description of the project/related repositories and then a link to the github.io for setup.

**Comment by jkeat** [comment]
@kadinzhang ok nice, i really like that format 👍 

let's use this branch to fully transition to that sort of layout. for now, i'll assign this to myself and take care of removing the README and replacing it with the basic project info and relevant links.

**Comment by jkeat** [comment]
Sticking with README docs for now

**Pull request closed without merging**
